import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GoogleGenAI } from '@google/genai';
import { CreateAiDto, StreamingAiDto } from './dto/create-ai.dto';

@Injectable()
export class AiService {
  private readonly logger = new Logger(AiService.name);
  private readonly ai: GoogleGenAI;

  constructor(private readonly configService: ConfigService) {
    const apiKey = this.configService.get<string>('GEMINI_API_KEY');

    if (!apiKey) {
      this.logger.warn(
        'GEMINI_API_KEY is not set. Please set it in your .env file.',
      );
      throw new Error(
        'GEMINI_API_KEY environment variable is required. Please set it in your .env file.',
      );
    }

    this.ai = new GoogleGenAI({
      apiKey: apiKey,
    });

    this.logger.log('Gemini AI initialized successfully');
  }

  /**
   * Standard request: Waits for the entire response to finish.
   */
  async getSimpleResponse(createAiDto: CreateAiDto) {
    try {
      const model = createAiDto.model || 'gemini-3-flash-preview';
      const prompt = this.promtGeneratorForGemini(createAiDto.prompt);

      const response = await this.ai.models.generateContent({
        model: model,
        contents: prompt,
      });

      const content = response.text;
      if (!content) {
        throw new Error('No content received from Gemini API');
      }

      return {
        content: content,
        model: model,
        usage: {
          promptTokens: 0,
          completionTokens: 0,
          totalTokens: 0,
        },
      };
    } catch (error) {
      this.logger.error('Error fetching completion:', error.message);
      throw error;
    }
  }

  /**
   * Streaming request: Yields tokens as they are generated (Typewriter effect).
   */
  async *getStreamingResponse(streamingAiDto: StreamingAiDto) {
    try {
      const model = streamingAiDto.model || 'gemini-3-flash-preview';
      const prompt = this.promtGeneratorForGemini(streamingAiDto.prompt);

      const stream = await this.ai.models.generateContentStream({
        model: model,
        contents: prompt,
      });

      for await (const chunk of stream) {
        const text = chunk.text || '';
        if (text) {
          yield text;
        }
      }
    } catch (error) {
      this.logger.error('Streaming Error:', error.message);
      throw error;
    }
  }

  /**
   * Generate prompt for Gemini — optimized for detailed, step-by-step
   * informational content that satisfies Google's Helpful Content guidelines.
   */
  private promtGeneratorForGemini(prompt: string): string {
    return `
You are an experienced technical writer and subject-matter expert.
Your job is to write a genuinely helpful, in-depth article that a real person would bookmark and share.

TOPIC: ${prompt}

═══════════════════════════════════════════
CONTENT QUALITY RULES (most important)
═══════════════════════════════════════════
1. Write from first-hand knowledge. Include specific details only someone with real experience would know — exact settings, common pitfalls, "what I wish I knew" insights.
2. Every claim must be actionable. Instead of "use a good password", write "use a passphrase of 4+ random words generated by a password manager like Bitwarden or 1Password".
3. Add concrete examples, sample code, real tool names, or exact numbers wherever possible.
4. Anticipate follow-up questions and address them inline.
5. If there are multiple approaches, briefly compare their trade-offs so the reader can pick the right one.
6. Mention limitations, edge cases, and when this advice does NOT apply.

═══════════════════════════════════════════
ARTICLE STRUCTURE (follow this outline)
═══════════════════════════════════════════
Use semantic HTML. No markdown. No emojis.

<h2>Introduction</h2>
- State the problem or goal clearly in 2-3 sentences.
- Explain who this guide is for and what they will accomplish.
- Mention prerequisites or what the reader needs before starting.

<h2>Key Concepts (if needed)</h2>
- Define any terms or background the reader needs.
- Keep it brief — just enough so the steps make sense.

<h2>Step-by-Step Guide</h2>
- Use <h3>Step 1: [Action verb] ...</h3>, <h3>Step 2: ...</h3> etc.
- Each step should explain WHAT to do, WHY it matters, and HOW to verify it worked.
- Include code snippets in <pre><code> blocks where relevant.
- Use <ul> or <ol> for sub-steps within a step.
- Add <strong>Tip:</strong> or <strong>Warning:</strong> callouts for important gotchas.

<h2>Common Mistakes to Avoid</h2>
- List 3-5 real pitfalls with explanations of why they happen and how to fix them.

<h2>Advanced Tips (optional)</h2>
- For readers who want to go further.

<h2>Summary</h2>
- Recap the key takeaways in 3-5 bullet points.
- Suggest a logical next step or related topic.

═══════════════════════════════════════════
WRITING STYLE
═══════════════════════════════════════════
- Active voice. Short, confident sentences.
- Write like you are teaching a smart colleague, not selling.
- No buzzwords, no fluff, no filler intros like "In today's fast-paced world...".
- No AI clichés: "delve", "crucial", "landscape", "navigate", "comprehensive guide to".
- Vary sentence length naturally. Mix short punchy lines with occasional longer explanations.
- Use "you" to address the reader directly.
- Target 2000-3500 words of genuinely useful content. Depth over breadth.

═══════════════════════════════════════════
SEO RULES
═══════════════════════════════════════════
- Title: Include the primary keyword naturally. Keep under 60 characters.
- Excerpt: A compelling 150-160 character meta description that makes searchers click.
- Keywords: 8-12 long-tail keywords that real people search for (e.g. "how to set up Docker on Ubuntu" not just "Docker").
- Generate valid JSON-LD ArticleSchema and FAQPageSchema.
- FAQs: 5-8 genuine questions a reader would ask AFTER reading — not rehashes of the content.
  FAQ answers should be concise (2-3 sentences) and add new information.

═══════════════════════════════════════════
OUTPUT FORMAT
═══════════════════════════════════════════
Return ONLY valid JSON (no extra text, no markdown fences):

{
  "metadata": {
    "title": "string (under 60 chars)",
    "slug": "url-friendly-slug",
    "excerpt": "string (150-160 chars)",
    "author": "ME",
    "publishedAt": "ISO 8601 date",
    "readingTime": "X min read",
    "keywords": ["long-tail keyword 1", "..."],
    "ogTitle": "string",
    "ogDescription": "string"
  },
  "content": {
    "html": "<h2>...</h2><p>...</p>..."
  },
  "seo_technical": {
    "articleSchema": { valid JSON-LD Article },
    "faqSchema": { valid JSON-LD FAQPage }
  },
  "faqs": [
    { "question": "string", "answer": "string" }
  ]
}

CRITICAL:
- The JSON must be valid and parseable. Escape quotes in HTML strings properly.
- Do NOT wrap in markdown code fences.
- Do NOT add any text before or after the JSON object.
- Base content strictly on the topic. Do not invent statistics or cite fake sources.
`;
  }

  // Legacy methods (kept for backward compatibility)
  create(createAiDto: CreateAiDto) {
    return this.getSimpleResponse(createAiDto);
  }

  findAll() {
    return `This action returns all ai`;
  }

  findOne(id: number) {
    return `This action returns a #${id} ai`;
  }

  update(id: number, updateAiDto: any) {
    return `This action updates a #${id} ai`;
  }

  remove(id: number) {
    return `This action removes a #${id} ai`;
  }
}
